spring:
  application:
    name: api-gateway
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    user-service:
      path: /api/v1/users/**
      url: http://localhost:8082/users
